---
- name: Ensure swarmpit data directory exist
  become: true
  file:
    group: "{{ swarmpit__deploy_group }}"
    owner: "{{ swarmpit__deploy_user }}"
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ swarmpit__deploy_dir }}"
    - "{{ swarmpit__data_dir }}"

- name: Copy files
  become: true
  template:
    dest: "{{ swarmpit__deploy_dir }}/swarmpit.yml"
    group: "{{ swarmpit__deploy_group }}"
    owner: "{{ swarmpit__deploy_user }}"
    src: "templates/swarmpit.yml.j2"
  when: swarmpit__state == "started"

- name: Start swarmpit services
  command: docker stack deploy -c swarmpit.yml swarmpit
  args:
    chdir: "{{ swarmpit__deploy_dir }}"
  when: swarmpit__state == "started"

- name: Stop swarmpit services
  command: docker stack rm swarmpit
  args:
    chdir: "{{ swarmpit__deploy_dir }}"
  when: swarmpit__state == "stopped"
